### ISSUE TITLE
Lazy Loading 

### ISSUE THREAD

**Issue by Liahus1996** [hjalmers/angular-generic-table#142]
If Lazy loading is caching data in the table why does the loading time remains the same like the data is being requested from the server again ?

**Comment by hjalmers** [comment]
Hi @Liahus1996, caching is disabled by default when lazy loading so you need to set caching to true in [options](https://github.com/hjalmers/angular-generic-table/wiki/Options).

**Comment by Liahus1996** [comment]
How does search work in this case , since we are not going to load all the data at once ?

**Comment by hjalmers** [comment]
You have to implement search/filtering server-side as the table won't have access to the whole dataset. You can take a look at [this mock service  ](https://private-730c61-generictable.apiary-mock.com/data) for a rough idea on how to move forward. It's missing information about search/filtering and it's just an example how the response object could look like. But your response object should contain the search term(s) passed to the server, and to highlight the hits in the table you need to set/update `info.searchTerms` to the actual one returned from the server.

I've added a section in the wiki [here](https://github.com/hjalmers/angular-generic-table/wiki/Lazy-loading-and-table-info) with some more info. The [example](https://hjalmers.github.io/angular-generic-table/lazy) uses the same principle too, although the search terms are fixed.

**Comment by Liahus1996** [comment]
Am not getting the sorting icons on my Table headers , what do i do ?

**Comment by hjalmers** [comment]
@Liahus1996 my guess is that you haven't added any styling for the headings. To get basic styling (small arrows for sort ascending and sort descending) you can add the stylesheet provided with generic table, ex. if you're using sass, you could import the generic-table sass file like this:

```sass

@import "~@angular-generic-table/core/scss/generic-table";
```

or if you prefer plain old css it's available here:
```js
~@angular-generic-table/core/css/generic-table.css"
```

If you'd like custom icons check out the css used in my example here:
https://github.com/hjalmers/angular-generic-table/blob/master/src/examples.scss

**Comment by psined1** [comment]
What is the difference between filtering and searching? In the advanced example, the search seems to highlight and filter at the same time, whereas applying the predefined filter only shows with record matching the search string. I'm trying to get the idea which one should I use for lazy loading from the server - searchTerms or filter or both.

**Comment by hjalmers** [comment]
@psined1, when using lazy loading it’s up to you how you want to use it but the general idea behind it and how it works when filtering and/or searching client side is that filters are applied before search. To make it more performant, the table only looks for matches inside strings after filters have been applied i.e. instead of going through all rows to find matches it only goes through the ones left when the filters have been applied. You might want to differentiate the two so they user knows how many records match the applied filters and how many are left out of those after searching through them using a string. Not sure if that makes any sense but if you want the user to be able to choose between a fixed set of values and filter/search the records using a free text string you’ll want to use both.
