### ISSUE TITLE
GtExpandedRow doesn't attach to new rows

### ISSUE THREAD

**Issue by Vorathe** [hjalmers/angular-generic-table#169]
Steps to reproduce:

1. https://hjalmers.github.io/angular-generic-table/advanced
2. Click Actions -> Add Data
3. Click caret to toggle expanded row
4. Row doesn't expand or select when clicked

**Comment by hjalmers** [comment]
Sorry for the late reply, that definitely looks like a bug. Will look into it:) Thanks for reporting:)

**Comment by hjalmers** [comment]
@Vorathe, even thought the code used to work in the past I realize that it probably stopped working some time ago when I changed the way the table manipulates arrays and objects. Objects and arrays should be immutable (currently the table is manipulating objects/arrays) so the example would work if you'd pass a new instance of the data i e. instead of:
```ts
// push data to data array (doesn't work).
    this.configObject.data.push({ 
            'id': this.configObject.data.length + 1, 
            'first_name': firstName, 
            'last_name': lastName, 
            'email': firstName + '.' + lastName + '@some_email_address.xyz', 
            'gender': gender, 
            'favorite_color': favoriteColor, 
    }); 
```

this would actually work: 
```ts
// create a new instance of the array (triggers everything correctly in generic table).
    this.configObject.data = [...this.configObject.data, { 
            'id': this.configObject.data.length + 1, 
            'first_name': firstName, 
            'last_name': lastName, 
            'email': firstName + '.' + lastName + '@some_email_address.xyz', 
            'gender': gender, 
            'favorite_color': favoriteColor, 
    }]; 
```

But I've add a new function to add rows (and to delete rows as well) and updated the examples accordingly as the table should handle these things.
