### ISSUE TITLE
Use tslint-config-prettier

### ISSUE THREAD

**Issue by hjalmers** [hjalmers/angular-generic-table#223]
Read more about it [here](https://github.com/alexjoverm/tslint-config-prettier)

**Comment by mklein994** [comment]
You had mentioned elsewhere that you like prettier because it can format on save. With the [TSLint plugin](https://marketplace.visualstudio.com/items?itemName=eg2.tslint) for VSCode, you can do the same thing by adding
```json
{
    "tslint.autoFixOnSave": true
}
```
to your user settings.

There should be a similar option somewhere in WebStorm's settings.
