### ISSUE TITLE
Lazy loading with Checkbox selection not working 

### ISSUE THREAD

**Issue by LokeshBoran** [hjalmers/angular-generic-table#244]
I think there is an issue with Lazy Loading and Checkbox Selection method. If I combine both the examples checkbox selection is not working properly and sometimes paging is also not visible. I am sharing an live example for the same problem - 
[example](https://stackblitz.com/edit/angular-generic-table-lazyloading-with-checkbox?file=src%2Fapp%2Fapp.component.ts)

## Step-1
1.  Click on select all then click deselect all, its working fine.
2. Click on any one or row checkbox then click select all checkbox, Its working fine. Now, If I click on deselect all this is not working or you can say deselect-all event is not fired.

If you find any solution plz let me know.
Thanks in advance. :)

**Comment by LokeshBoran** [comment]
@hjalmers still there is the issue. I updated the example with the latest build still I am able to reproduce the same issue.

**Comment by LokeshBoran** [comment]
Hey, @hjalmers  [https://github.com/hjalmers/angular-generic-table/commit/d5ab4f7e99bfbe2ee98fadb615a62152476b4b7e](d5ab4f7) there is serious issues occurs.
## Step to reproduce - 
1. First select 2 or 3 checkbox and then select all it will always push current page size data into `selectedRows` every time when i click on select/deselect all checkbox.

**Comment by hjalmers** [comment]
@LokeshBoran, I haven’t published a new version containing the fix yet so you you have to hang tight a little while longer. I’ll open this issue again until it’s published though:)

**Comment by hjalmers** [comment]
@LokeshBoran the fix is now available with version 4.15.0. Please note however that it's a bit hard for the table to know the state of each row when it's loaded from the server. I'd probably suggest adding a property on each row and store the state on the server with the rest of the data if you want to persist the state. If you enable caching like I've done in [this example](https://stackblitz.com/edit/angular-generic-table-lazyloading-with-checkbox-tq7c22) it will work (not the select all option for data that hasn't been loaded yet though).

The problem with caching is that if the data on the server changes the table won't update when you paginate between pages that has already been loaded/cached. If caching is disabled on the other hand, the table will request new data when you go to a new page and the rows will get new row ids at the same time, that's also the reason why the state is not persisted.

We could keep the ids and just update the data but what if a new row has been added on the server and/or the order has changed? We can't just rely on row or page indexes to keep the states in sync when the records are fetched from the server and without a unique id it's very hard to sync a local record with a record received from the server. I've added the ability to set a custom row id #245 which simplifies syncing state with server as well.

**Comment by LokeshBoran** [comment]
@hjalmers thanks a lot for your changes. Looking forward to seeing more changes related to usability and stability of the library. 
And yes if I want to deselect checkbox on page-change than on [gt-page-changed-lazy](https://github.com/hjalmers/angular-generic-table/wiki/Events) event I have to call [deselectAllRows](https://github.com/hjalmers/angular-generic-table/wiki/Methods) method.

**Comment by hjalmers** [comment]
No problem, yeah there are some manual steps involved now like deselecting rows if data set is replaced etc. I was also thinking about what should happen if you've checked "check all" and you go to the next page, the server will fetch data from the sever and I guess it should select them if they're not already selected otherwise the state of the select all checkbox won't be correct.
