### ISSUE TITLE
generic table is not working inside of ng-template

### ISSUE THREAD

**Issue by rcanpahali** [hjalmers/angular-generic-table#268]
this is my code: 
`        <ng-template *ngIf="true">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <generic-table #table1 [gtSettings]="gt.settings" [gtClasses]="'small'" [gtInfo]="gt.info" [gtOptions]="gtOptions" [gtFields]="gt.fields" [(gtData)]="gt.data" (gtEvent)="trigger($event)"></generic-table>
                </div>
            </div>
            <div class="text-center">
                <gt-pagination [gtClasses]="'justify-content-center'" [genericTable]="table1"></gt-pagination>
            </div>
        </ng-template>`

When i remove ng-template, it's working... Is this bug ?

**Comment by hjalmers** [comment]
It might be, because it should work with ng-template so if it doesn’t we should fix it I think. I don’t have access to a computer at the moment and won’t have access to one for another week I’m afraid, but it might have something to do with the object references not being updated/set correctly when using ng-template. You could try skipping the `gt` object and just refer directly to `settings`, `fields` and `data` or declare them at the same time `true` becomes `true`  not sure it works but I think I’ve come across this before at least.

**Comment by rcanpahali** [comment]
Thanks for your answer, It's not a problem for my situation. I used ngIf in my Div tag and fixed the issue. But i just wanted to tell if its really a bug or not. :)
