### ISSUE TITLE
Disable specific checkbox

### ISSUE THREAD

**Issue by brampeirs** [hjalmers/angular-generic-table#278]
Is there a way to disable a checkbox after I use initialSelectedItems. So the checkbox for that specific row is checked on by default and can not be checked off by the user?

If that is not possible, maybe a way to capture when a checkbox is toggled or row is selected. So I can hook into that event and run some logic on and turn the checkbox back on.

**Comment by hjalmers** [comment]
Hi and sorry for the late reply. It's not supported out of the box but I guess it would be pretty easy to create a custom component instead of using the checkbox type option. You should be able to reuse a lot from the "built in" [checkbox component  ](https://github.com/hjalmers/angular-generic-table/blob/master/%40angular-generic-table/core/components/gt-checkbox/gt-checkbox.component.ts).

**Comment by brampeirs** [comment]
Thanks for your answer. I will try that.
