### ISSUE TITLE
Transitioning to the Angular 6+ is not possible for Angular CLI

### ISSUE THREAD

**Issue by demid5111** [hjalmers/angular-generic-table#284]
Hello,

I have a project that is working on Angular 5.
The table component is working like a charm.

However, after I update the project to Angular 6, by using [this link](https://stackoverflow.com/questions/50814546/migration-angular-5-to-6-ng-update-hanging-and-do-nothing)

I get the following error:

>Package "@angular-generic-table/core" has an incompatible peer dependency to "@angular/core" (requires "^4.0.0" (extended), would install "6.1.10").
>Package "@angular-generic-table/core" has an incompatible peer dependency to "@angular/common" (requires "^4.0.0" (extended), would install "6.1.10").

Could you please help?

**Comment by Crash1988** [comment]
Hi @demid5111 , in angular cli documentation you can find parameters when running ng update for this kind of errors,
please try 
`ng update --all --force` 
It basically avoids/ignores all the dependency-checks and updates all the packages wherever applicable.
I hope it helps.
Thanks

**Comment by demid5111** [comment]
Does that mean that tables will be still working with Angular 6? пятница, 02 ноября 2018г., 23:30 +03:00 от Dennis Gonzalez  notifications@github.com :

**Comment by demid5111** [comment]
however, I get the error as updating to the 6th version also requires to use rxjs v6

**Comment by Crash1988** [comment]
@demid5111 Hi, this is not my library, Im just trying to help, 
Did you try to run in your angular folder?
` npm install rxjs-compat tether --save`
That library is for compatibility to previous version of rxjs lib( i read somewhere they plan to removed in next versions but no sure is they did it on version 7)
i have it running on version 6 with no problem and i use very complex concepts like lazy loading in some cases, customs header components and custom rows.
Also if you can't make it work check other alternatives like material [https://material.angular.io/components/table/examples](https://material.angular.io/components/table/examples)
Thanks

**Comment by hjalmers** [comment]
Sorry for being a little late to the party and thanks @crash1988 for helping out:) It should work just fine with angular 6 following the steps crash explained above. However I haven’t tried using it with angular 7 just yet but it should work too as there are no major breaking changes between angular 6 and 7 that should affect angular-generic-table.

That said I hope I’ll get some time soon to release a new version using the latest version of angular including version 6 of rxjs.

There are a lot of things on the list of things that could be improved since both angular and angular cli has come a long way since this library was written. Not to mention some interesting things to come with the new ivy compiler that hopefully will be release soon:)

Anyways, let me know if the above solotion doesn’t work for you @demid5111 until a new version is released:)

**Comment by Crash1988** [comment]
@hjalmers thanks for the response, please create a new branch like you said https://github.com/hjalmers/angular-generic-table/issues/253#issuecomment-393270462  and i will try to help, i know you have to change a lot since now we can move everything to a library but once that step is done the rest should be easier, and also update the rxjs

**Comment by hjalmers** [comment]
Yeah first step would just be to use latest angular version and update rxjs (hopefully I'll find some time to do it this week). I just tried using the library with latest version of angular (7.0.3) and I can confirm that it works when doing:

```
npm install rxjs-compat tether --save
```

**Comment by hjalmers** [comment]
#253
