### ISSUE TITLE
Parameterized CustomComponent

### ISSUE THREAD

**Issue by rfrancisco** [hjalmers/angular-generic-table#94]
We have dozens of lists in our application where we plan to use this table, actually we will be using a wrapper component that encapsulates this table. But there are 2 scenarios that we are struggling with:

1 - Adding a column that shows a checkbox for row selection with the option to select/deselect all rows with a checkbox in the column header. Is it possible to create a custom component to allow this?

2 - (And the most important one) All of our tables have an options column, that contains a drop-down menu with actions specific to the table particular context. Our ideia would be to have a generic customControl that would render the options menu and where the actions would be configurable. The problem is that we dont see a way to pass configuration to a GtCustomControl since we cant provide an instance of the component, only the type. Is there a way to do this?

One last thing. When we dont have any data and we pass an empty array the table shows the message 'Loading...'. What do we need to pass so that the 'No data' message is rendered instead?

**Comment by hjalmers** [comment]
Hi, and sorry for the late reply...

1. Regarding your first question I think it's a pretty common use case so we should definitely add an example on how to achieve it and perhaps make it even easier. There are multiple ways to do it, one and perhaps the simplest would probably be to just apply a style to the row when it's selected, making it look like a select box or perhaps even render a real checkbox like [this](https://embed.plnkr.co/XPWjIZE0X3iHhI1HuGO1/). I have to admit that it's a bit hacky and it doesn't solve the checkbox in the table header. But I've create a separate issue for this  #96 so I'll see if I can't come up with something smarter.

2. Have you looked at [this example](https://hjalmers.github.io/angular-generic-table/custom-column)? It might not be super trivial, but you should be able to accomplish what you want using a service that you inject in your custom component. Since you're able to access the row you could also pass custom properties for the table or each row to the service. If the table needs to be updated/refreshed it should also subscribe to the same service.

3. Regarding the loading message, I think it might be a bug so I'll look into it straight away. If an empty array is passed it should display no data but I just tried it myself and I also get the loading message so I think we've introduced a bug somewhere. I've created a separate issue here #95

**Comment by rfrancisco** [comment]
Hi, any updates regarding this?

Thanks

**Comment by hjalmers** [comment]
Hi @rfrancisco, sorry I haven't had time to look at #96 (the checkboxes) yet but it's on my list:)

Regarding your second question, have you tried the approach I mentioned in my earlier reply? If not another pretty easy option would be to make use of the [inline edit feature](https://hjalmers.github.io/angular-generic-table/inline-editing) and subscribe to the 'gt-row-updated' event and get the desired action from the event. It's not really meant to be used for this but it would work and once the action is applied the value could be reset too. 

The last issue with the loading text should have been resolved too:)

**Comment by rfrancisco** [comment]
Hi @hjalmers,

Looking at the example you pointed out i was able to implement the configurable dropdown menu. 

Thanks for all the help.
